dist: xenial
language: node_js
node_js:
  - "8.0"
services:
  - redis-server
cache:
  directories:
  - node_modules
git:
  depth: 3
before_install:
  - ./travis-install.sh
script:
  - npm test
after_success:
  - npm run coverage