{{ with $.Values.worker }}
{{ $fullName := include "iot.fullnameWorker" $ }}
{{ $selectorLabels := include "iot.selectorLabelsWorker" $ }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    {{ include "iot.labels" $ | nindent 4 }}
data:
  DEBUG: {{ .debug | quote }}
  {{ with .topics }}
  MEASUREMENT_TOPIC: {{ .measurement }}
  MEASUREMENT_CHANGE_TOPIC: {{ .measurementChange }}
  EVENT_TOPIC: {{ .event }}
  {{ end }}
  {{ with .measurementChange }}
  MEASUREMENT_CHANGE_GROWTH_RATE_THRESHOLD: {{ .growthRateThreshold | quote }}
  MEASUREMENT_CHANGE_PAST_INTERVAL_IN_HOURS: {{ .pastIntervalHours | quote }}
  {{ end }}
  {{ with .mongo }}
  MONGO_DB: {{ .db }}
  MONGO_URL: {{ .url }}
  {{ end }}
  {{ with .mqtt }}
  MQTT_BROKER_HOST: {{ .host }}
  MQTT_BROKER_PORT: {{ .port | quote }}
  {{ end }}
  BIOT_URL: {{ .biotUrl }}
{{ end }}