{{ with $.Values.thing }}
{{ $fullName := include "iot.fullnameThing" $ }}
{{ $selectorLabels := include "iot.selectorLabelsThing" $ }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName  }}
  labels:
    {{ include "iot.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ $selectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{ $selectorLabels | nindent 8 }}
    spec:
      containers:
        - name: {{ $fullName  }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          {{ with .resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end }}
          ports:
            - containerPort: {{ .service.port }}
          envFrom:
            - configMapRef:
                name: {{ $fullName }}
    {{ with .nodeSelector }}
    nodeSelector:
      {{ toYaml . | nindent 8 }}
    {{ end}}
{{ end }}