{{ with $.Values.thing }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iot.fullnameThing" $ }}
  labels: 
    {{ include "iot.labels" $ | nindent 4 }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
  selector: 
    {{ include "iot.selectorLabelsThing" $ | nindent 4 }}
{{ end }}