language: node_js
node_js:
  - "12.0"
cache:
  directories:
  - node_modules
  - ./**/**/node_modules
stages:
  - lint
  - build
jobs:
  include:
    - stage: lint 
      script: ./scripts/ci-lint.sh
    - stage: build 
      script: ./scripts/ci-build.sh