language: node_js
node_js:
  - "12.0"
cache:
  directories:
    - node_modules
services:
  - docker
stages:
  # - lint
  - build
  - test
jobs:
  include:
    # - stage: lint
    #   name: Lint
    #   script: npm run lint
    - stage: build 
      name: Build
      script: npm run build
    - state: test
      name: Test
      before_install: ./scripts/ci-docker.sh
      script: npm test