version: "3"
services:
  mongo:
    image: mongo:4.2.3
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - ./data/mongo:/data/db
    restart: unless-stopped
  redis:
    image: redis:5.0.9-alpine3.11
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto:2.0.9
    ports:
      - "${MQTT_BROKER_PORT}:${MQTT_BROKER_PORT}"
    volumes:
      - ./data/mosquitto/data:/mosquitto/data
      - ./services/mosquitto:/mosquitto/config
    restart: unless-stopped
