version: '3'
services:
  nginx:
    build: services/nginx
    ports:
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
      - "${NGINX_MQTT_PORT}:${NGINX_MQTT_PORT}"
    depends_on:
      - back
    restart: always
  back:
    build: packages/back
    env_file: .env
    expose:
      - "${BACK_PORT}"
    restart: always
  front:
    build: 
      context: packages/front
      args:
        FRONT_PORT: "${FRONT_PORT}"
    expose:
      - "${FRONT_PORT}"
    depends_on:
      - back
    restart: always
  biot:
    build: packages/biot
    env_file: .env
    expose:
      - "${BIOT_PORT}"
    depends_on:
      - back
    restart: always
  worker:
    build: packages/worker
    env_file: .env
    expose:
      - "${WORKER_PORT}"
    restart: always