export default {
  env: "test",
  nodePort: 9000,
  mongoUrl: "mongodb://localhost:27017/IoT-test",
  redisUrl: "redis://localhost:6379",
  mqttBrokerHost: "localhost",
  mqttBrokerPort: 1883,
  mqttBrokerUsername: undefined,
  mqttBrokerPassword: undefined,
  defaultCacheInSeconds: 10,
  statsCacheInSeconds: 1,
  maxDefaultNearbyDistanceInMeters: 10000,
  maxNumOfThingsInStatsResults: 10,
  basicAuthUsers: {
    admin: "admin",
  },
  jwtSecret: "2SrZAfNgGhn7eff2P5hvPUdX",
  googleMapsKey: `${process.env.GOOGLE_MAPS_KEY}`,
  storeLogsInMongo: false,
  debug: true,
};
