export const TOGGLE_HAMBURGER_MENU = "TOGGLE_HAMBURGER_MENU";
export const TOGGLE_MAP_DIALOG = "TOGGLE_MAP_DIALOG";
export const TOGGLE_LANGUAGE_SELECTOR = "TOGGLE_LANGUAGE_SELECTOR";
export const SET_SHOW_ERROR = "SET_SHOW_ERROR";
