export const PARAM_SELECT = "PARAM_SELECT";
export const PARAM_UPDATE = "PARAM_UPDATE";
export const PARAM_RESET = "PARAM_RESET";
export const PARAM_REQUEST = "PARAM_REQUEST";
export const PARAM_REQUEST_SUCCESS = "PARAM_REQUEST_SUCCESS";
export const PARAM_REQUEST_ERROR = "PARAM_REQUEST_ERROR";
export const PARAM_ITEMS_UPDATED = "PARAM_ITEMS_UPDATED";
export const PARAM_DISABLE = "PARAM_DISABLE";
