export const THINGS_UPDATED = "THINGS_UPDATED";
export const THING_SELECTED = "THING_SELECTED";
export const THINGS_REQUEST = "THINGS_REQUEST";
export const THINGS_REQUEST_SUCCESS = "THINGS_REQUEST_SUCCESS";
export const THINGS_REQUEST_ERROR = "THINGS_REQUEST_ERROR";
export const SHOW_THING_NOT_FOUND_ERROR = "SHOW_THING_NOT_FOUND_ERROR";
