export const THING_FILTER_SELECT = "THING_FILTER_SELECT";
export const THING_FILTER_UPDATED = "THING_FILTER_UPDATED";
export const THING_FILTERS_REQUEST = "THING_FILTERS_REQUEST";
export const THING_FILTERS_REQUEST_SUCCESS = "THING_FILTERS_REQUEST_SUCCESS";
export const THING_FILTERS_REQUEST_ERROR = "THING_FILTERS_REQUEST_ERROR";
export const THING_FILTERS_UPDATED = "THING_FILTERS_UPDATED";
