apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{ include "redis.labels" . | nindent 4 }}
spec:
  selector:
    {{ include "redis.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.port }}