{{ with $.Values.biot }}
{{ $fullName := include "iot.fullnameBiot" $ }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    {{ include "iot.labels" $ | nindent 4 }}
data:
  DEBUG: {{ .debug | quote }}
  BIOT_SERVICE_PORT: {{ .service.port | quote }}
  BACK_URL: {{ .backUrl }}
  {{ with .growthRate }}
  GROWTH_RATE_HIGH_ABSOLUTE_THREESHOLD: {{ .highAbsoluteThreshold | quote }}
  GROWTH_RATE_MODERATE_ABSOLUTE_THREESHOLD: {{ .highAbsoluteThreshold | quote }}
  {{ end }}
  {{ with .temperature }}
  HIGH_TEMPERATURE_THRESHOLD: {{ .highThreshold | quote }}
  LOW_TEMPERATURE_THRESHOLD: {{ .lowThreshold | quote }}
  TEMPERATURE_PREFIX: {{ .prefix }}
  {{ end }}
  {{ with .humidity }}
  HIGH_HUMIDITY_THRESHOLD: {{ .highThreshold | quote }}
  LOW_HUMIDITY_THRESHOLD: {{ .lowThreshold | quote }}
  HUMIDITY_PREFIX: {{ .prefix }}
  {{ end }}
  {{ with .topics }}
  MEASUREMENT_CHANGE_TOPIC: {{ .measurementChange }}
  MEASUREMENT_TOPIC: {{ .measurement }}
  {{ end }}
{{ end }}