{{ $fullName := include "mosquitto.fullname" . }}
{{ $selectorLabels := include "mosquitto.selectorLabels" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName  }}
  labels:
    {{ include "mosquitto.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ $selectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{ $selectorLabels | nindent 8 }}
    spec:
      containers:
        - name: {{ $fullName  }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ with .resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end }}
          ports:
            - containerPort: {{ .Values.port }}
