mongodb:
  image:
    repository: mongo
    tag: 4.4.4
  architecture: standalone
  auth:
    enabled: false
  persistence:
    enabled: true
    size: 8Gi
    mountPath: /data/db
  metrics:
    enabled: false

prometheus-mongodb-exporter:
  image:
    repository: mmontes11/mongodb-prometheus-exporter
    tag: v0.12.0
  extraArgs:
    - --collect.collection
    - --collect.database
    - --collect.indexusage
    - --collect.topmetrics
    - --collect.connpoolstats
  port: "9113"
  service:
    port: 9113
    type: ClusterIP
  livenessProbe:
    httpGet:
      path: /
      port: metrics
    initialDelaySeconds: 10
  readinessProbe:
    httpGet:
      path: /
      port: metrics
    initialDelaySeconds: 10
  mongodb:
    uri: "mongodb://iot-mongo:27017"
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    namespace: monitoring
    additionalLabels:
      release: kube-prometheus-stack
