nameOverride: ""
fullnameOverride: ""

image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: 6.2.1

storage: 1Gi

port: 6379

resources: {}

nodeSelector: {}

prometheus-redis-exporter:
  image:
    repository: mmontes11/redis-prometheus-exporter
    tag: v1.7.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9121
  redisAddress: redis://redis:6379
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s
    timeout: 10s
    labels:
      release: prometheus
