name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Setup Test
        env:
          ENV_TEST: ${{ secrets.ENV_TEST }}
        run: |
          echo "$ENV_TEST" > .env
          cp .env packages/back
          docker-compose up -d
          docker ps -a

      - name: Test
        run: npm run test
