name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Setup CI
        env:
          ENV_TEST: ${{ secrets.ENV_TEST }}
        run: ./scripts/ci.sh

      - name: Test
        run: npm run test
